version: '3.8'
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: documind-postgres
    environment:
      POSTGRES_DB: documind_db
      POSTGRES_USER: documind_user
      POSTGRES_PASSWORD: documind_pass
    ports:
      - "5433:5432"
    volumes:
      - documind_data:/var/lib/postgresql/data

volumes:
  documind_data: